# Generated by Django 3.1.4 on 2021-01-11 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(help_text='Enter field documentation', max_length=32)),
                ('name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('price', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Enter field documentation', max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Enter field documentation', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_to_customer', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_to_item', to='catalog.item', verbose_name='item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
